name: dialysis
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+7

environment:
  
  sdk: '>=2.18.6'

dependencies:
  flutter:
    sdk: flutter

  # SDK extensions
  meta: ^1.7.0

  # System
  path_provider: ^2.0.11
  path: ^1.8.2
  platform_info: ^3.2.0
  device_info_plus : ^8.0.0
  package_info_plus: ^3.0.2
  connectivity_plus: ^3.0.2

  # Data manipulation
  stream_transform: ^2.1.0

  # BLoC
  bloc: ^8.1.0

  # Helper BLoC
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.0-dev.2
  hydrated_bloc: ^9.0.0

  # Flutter integrations bloc
  flutter_bloc: ^8.1.1


  # Code generation
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  # Internationalization
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter 


  logger: ^1.1.0
  # Logging
  sentry_flutter: ^6.18.1
  # stack_trace: ^1.11.0


  # Persistance
  shared_preferences: ^2.0.15
  sqflite_sqlcipher: ^2.1.1+1

  # HTTP
  dio: ^4.0.6
  dio_log: ^2.0.4

  # Navigation
  go_router: ^6.0.0

  # Native
  url_launcher: ^6.1.7
  share_plus: ^6.3.0

  

  # Helper for UI
  flash: ^2.0.5
  lottie: ^2.1.0
  flutter_native_splash: ^2.2.16
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  flex_color_scheme: ^6.1.1
  introduction_screen: ^3.1.1
  syncfusion_flutter_pdfviewer: ^20.4.38
  syncfusion_flutter_charts: ^20.4.38
  google_fonts: ^3.0.1

  # TEST
  device_preview: ^1.1.0
  feedback: ^2.5.0

  # Validation
  formz: ^0.4.1
  mask_text_input_formatter: ^2.4.0
  crypto: ^3.0.2


 # firebase
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.8
  firebase_remote_config: ^3.0.8
  # firebase_messaging: ^14.2.0
  cloud_firestore: ^4.3.0
  firebase_storage: ^11.0.9
  firebase_in_app_messaging: ^0.7.0+9
  firebase_analytics: ^10.0.8







dev_dependencies:



  # Analyzer extensions
  dart_code_metrics: ^5.3.0
  very_good_analysis: ^3.1.0


  # Code generation
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.5.4


# Tests
  #flutter_driver:
  #  sdk: flutter
  #integration_test:
  #  sdk: flutter
  #flutter_test:
  #  sdk: flutter
  coverage: ^1.6.1
  # test: ^1.22.1
  #bloc_test: ^8.1.0
  #mockito: ^5.1.0
  #build_test: ^2.1.5


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/lottie/
    - assets/image/
    - assets/db/


# flutter pub get && flutter pub run flutter_native_splash:create
# flutter_native_splash:
#   android: true
#   ios: true
#   web: true
#   desktop: true
#   color: "#141617"
#   # color_dark: "#141617"
#   image: assets/icon_splash/splash.png

