// ignore_for_file: non_constant_identifier_names

import 'package:freezed_annotation/freezed_annotation.dart';

part 'food_db_m.freezed.dart';
part 'food_db_m.g.dart';

@freezed
class FoodDbModel with _$FoodDbModel {
  const factory FoodDbModel({
    required int id,
    required int id_product,
    required int id_category,
    required int id_source,
    double? water,
    double? k_potassium,
    double? na_sodium,
    double? p_phosphorus,
    double? ca_calcium,
    double? proteins,
    double? calorie,
    double? carbohydrates,
    double? fats,
    double? feed_ash,
    double? a_vitamin,
    double? retinol,
    double? beta_carotene,
    double? b1_vitamin_thiamine,
    double? b2_vitamin_riboflavin,
    double? b5_vitamin,
    double? b6_vitamin_pyridoxine,
    double? b9_vitamin_folates,
    double? b12_vitamin_cobalamin,
    double? c_vitamin,
    double? e_vitamin,
    double? rr_vitamin,
    double? niacin,
    double? mg_magnesium,
    double? s_sulfur,
    double? cl_chlorine,
    double? fe_iron,
    double? i_iodine,
    double? co_cobalt,
    double? mn_manganese,
    double? cu_copper,
    double? mo_molybdenum,
    double? ni_nickel,
    double? se_selenium,
    double? f_fluorine,
    double? cr_chrome,
    double? zh_zinc,
    double? cholesterol,
    double? saturated_fatty_acids,
    double? myristina,
    double? palmitic,
    double? stearic,
    double? arachinova,
    double? mono_fatty_acids,
    double? palmitoleic,
    double? heptadecene,
    double? omega_9_oleic,
    double? omega_9_gadolein,
    double? poly_fatty_acids,
    double? linoleic,
    double? linolenic,
    double? arachidonic,
    double? omega_3_epk,
    double? omega_3_fatty_acids,
    double? omega_3_dpc,
    double? omega_6_fatty_acids,
    double? dietary_fiber,
    double? mono_di_saccharides,
    double? organic_acids,
    double? b4_vitamin,
    double? d_Vitamin_calciferol,
    double? h_vitamin_biotin,
    double? k_vitamin_phylloquinone,
    double? al_aluminium,
    double? sn_tin,
    double? sr_strontium,
    double? galactose,
    double? glucose_dextrose,
    double? lactose,
    double? essential_amino_acids,
    double? arginine,
    double? valin,
    double? histidine,
    double? isoleucine,
    double? leucine,
    double? lysine,
    double? methionine,
    double? methionine_cysteine,
    double? threonine,
    double? tryptophan,
    double? phenylalanine,
    double? phenylalanine_tyrosine,
    double? substitutable_amino_acids,
    double? alanine,
    double? aspartica_acid,
    double? glycine,
    double? glutamic_acid,
    double? proline,
    double? serin,
    double? tyrosine,
    double? cysteine,
    double? oil_4_0,
    double? capron,
    double? caprylic,
    double? caprine,
    double? laurin,
    double? pentadecane,
    double? margarine,
    double? myristolein,
    double? sucrose,
    double? trans_fats,
    double? starch_dextrins,
    double? ethyl_alcohol,
    double? si_silicon,
    double? b_bohr,
    double? v_vanadium,
    double? li_lithium,
    double? rb_rubidium,
    double? zr_zirconium,
    double? omega_9_eruca,
    double? omega_3_stioride,
    double? omega_3_Docosahexaeno,
    double? beta_sitosterol,
    double? begenova,
    double? fructose,
    double? maltose,
    double? phytosterols,
    double? ti_titan,
    double? hydroxyproline,
    double? lignoceric,
    double? betaine,
    double? monoun_trans_fats,
    double? cis_16_1,
    double? cis_18_1,
    double? trance_18_1,
    double? mixed_isomers,
    double? omega_6_cis,
    double? conjugated_linoleic_acid,
    double? omega_3_alpha_linolenic,
    double? d3_vitamin_cholecalciferol,
    double? alpha_carotene,
    double? cryptoxanthin_beta,
    double? lutein_zeaxanthin,
    double? beta_tocopherol,
    double? gamma_tocopherol,
    double? trance_16_1,
    double? cis_22_1,
    double? omega_9_nervone,
    double? trans_isomer_undefined,
    double? omega_6_gamma_linolenic,
    double? trance_18_3,
    double? omega_6_eicosadieno,
    double? eicosatrieno,
    double? omega_6_20_3,
    double? omega_6_docosatetraeno,
    double? lycopene,
    double? tocopherol_delta,
    double? polyun_trans_fats,
    double? tridecane_13_0,
    double? omega_3,
    double? pentadecene,
    double? caffeine,
    double? theobromine,
    double? trans_trans,
    double? menaquinone_4,
    double? campesterol,
    double? stigmasterol,
    double? e_vitamin_added,
    double? b12_vitamin_added,
    double? trance_22_1,
    double? dihydrophylloquinone,
    double? d2_vitamin_ergocalciferol,
    double? omega_6_20_4,
    double? omega_3_geneico,
    double? phosphorus_protein_ratio,
    double? kilojoule,
  }) = _FoodDbModel;

  /// Generate Class from Map<String, Object?>
  factory FoodDbModel.fromJson(Map<String, Object?> json) =>
      _$FoodDbModelFromJson(json);


}
